-- MySQL Script generated by MySQL Workbench
-- 01/02/17 18:09:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Prava`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Prava` ;

CREATE TABLE IF NOT EXISTS `Prava` (
  `idPrava` INT NOT NULL AUTO_INCREMENT,
  `Nazev` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idPrava`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Uzivatel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Uzivatel` ;

CREATE TABLE IF NOT EXISTS `Uzivatel` (
  `idUzivatel` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(20) NOT NULL,
  `Heslo` VARCHAR(20) NOT NULL,
  `Jmeno` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `idPrava` INT NOT NULL,
  `Smazano` INT ZEROFILL NULL,
  PRIMARY KEY (`idUzivatel`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC),
  INDEX `fk_Uzivatel_Prava1_idx` (`idPrava` ASC),
  CONSTRAINT `fk_Uzivatel_Prava1`
    FOREIGN KEY (`idPrava`)
    REFERENCES `Prava` (`idPrava`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stav`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stav` ;

CREATE TABLE IF NOT EXISTS `Stav` (
  `idStav` INT NOT NULL AUTO_INCREMENT,
  `Nazev` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStav`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prispevky`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Prispevky` ;

CREATE TABLE IF NOT EXISTS `Prispevky` (
  `idPrispevky` INT NOT NULL AUTO_INCREMENT,
  `idAutor` INT NOT NULL,
  `Nazev` VARCHAR(45) NOT NULL,
  `NazevSouboru` VARCHAR(45) NOT NULL,
  `Datum` TIMESTAMP(45) NULL DEFAULT CURRENT_TIMESTAMP,
  `Popis` VARCHAR(400) NOT NULL,
  `idStav` INT NOT NULL,
  `Smazano` INT ZEROFILL NULL,
  PRIMARY KEY (`idPrispevky`),
  INDEX `fk_Prispevky_Stav1_idx` (`idStav` ASC),
  CONSTRAINT `fk_Prispevky_Stav1`
    FOREIGN KEY (`idStav`)
    REFERENCES `Stav` (`idStav`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hodnoceni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hodnoceni` ;

CREATE TABLE IF NOT EXISTS `Hodnoceni` (
  `Uzivatel_idUzivatel` INT NOT NULL,
  `Prispevky_idPrispevky` INT NOT NULL,
  `Zpracovani` INT NOT NULL,
  `Obsah` INT NOT NULL,
  `Styl` INT NULL,
  PRIMARY KEY (`Uzivatel_idUzivatel`, `Prispevky_idPrispevky`),
  INDEX `fk_Uzivatel_has_Prispevky_Prispevky1_idx` (`Prispevky_idPrispevky` ASC),
  INDEX `fk_Uzivatel_has_Prispevky_Uzivatel_idx` (`Uzivatel_idUzivatel` ASC),
  CONSTRAINT `fk_Uzivatel_has_Prispevky_Uzivatel`
    FOREIGN KEY (`Uzivatel_idUzivatel`)
    REFERENCES `Uzivatel` (`idUzivatel`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uzivatel_has_Prispevky_Prispevky1`
    FOREIGN KEY (`Prispevky_idPrispevky`)
    REFERENCES `Prispevky` (`idPrispevky`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scvhaleni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Scvhaleni` ;

CREATE TABLE IF NOT EXISTS `Scvhaleni` (
  `idScvhaleni` INT NOT NULL AUTO_INCREMENT,
  `Nazev` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idScvhaleni`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
